### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jlegrone** [cretz/temporal-debug-go#1]
Please add a license to help support external use and allow godoc to be rendered at https://pkg.go.dev/github.com/cretz/temporal-debug-go.

Really excited about this project! 😄

**Comment by cretz** [comment]
:+1: Note, as kinda mentioned in the README, this is more experimental stuff. The code isn't really official and I wasn't really planning on retaining any kind of compatibility guarantees. I will add license and maybe more features on my next down time.
